# Generated by Django 4.0 on 2023-01-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlef', models.CharField(max_length=50)),
                ('metinf', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Professional_second',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('max_proje', models.CharField(max_length=50)),
                ('fiyati', models.IntegerField()),
                ('metin', models.CharField(max_length=50)),
                ('depolama_alani', models.CharField(max_length=50)),
                ('ek_bilgi', models.CharField(max_length=50)),
                ('ek_bilgi2', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
