# Generated by Django 4.0 on 2023-01-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_feature_professional_second_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional_second',
            name='bilgi2',
            field=models.BooleanField(default=False),
        ),
    ]
