# Generated by Django 4.0 on 2023-01-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_destlast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featurepricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ozellik1', models.CharField(max_length=50)),
            ],
        ),
    ]
