# Generated by Django 4.0 on 2023-01-30 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_featurepricing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featurepricing',
            old_name='ozellik1',
            new_name='ozellik',
        ),
    ]
